### PR TITLE
Reorganize code with OOP and some of PSR-2, PSR-4 standards without changing API

### PR DESCRIPTION
**Pull request by pchapl**
TODO: comments, tests, autoload

### CODE REVIEW

**Comment by nickbclifford** [comment]
Looks great! Did you get a chance to test it?

**Comment by pchapl** [comment]
I'll try to do phpunit-tests tomorrow. Manual testing both versions shows the same behavior for all tested cases

**Comment by nickbclifford** [comment]
Sounds good. I'll merge afterwards.

**Comment by pchapl** [comment]
fix it https://github.com/MiningPotatoes/PeriodicTable-API/pull/4

**Pull request merged**
